# Generated by Django 4.2.6 on 2024-01-05 18:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        (
            "dynamic_models",
            "loginSignup_0001_initial",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="loginsignupconfigmodel",
            name="object_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        )
    ]
