# Generated by Django 4.2.7 on 2024-02-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectstore',
            name='audit_log',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
