# Generated by Django 4.2.8 on 2024-01-14 04:58


from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ("dynamic_models", 'communication_0005_telephonyconfigmodel_telephonyagent_framesmodel_and_more')
    ]

    operations = [
        migrations.AddField(
            model_name='meetinghostmodel',
            name='host_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='meetinghostmodel',
            name='host_name',
            field=models.CharField(max_length=50, null=True),
        )
    ]
