# Generated by Django 4.2.5 on 2023-11-16 11:51

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid
import zelthy.apps.dynamic_models.fields
import zelthy.core.storage_utils


def create_default_active_status(apps, schema_editor):
    CommmunicationActiveModel = apps.get_model(
        "dynamic_models", "CommmunicationActiveModel"
    )
    CommmunicationActiveModel.objects.create()


class Migration(migrations.Migration):
    dependencies = [("appauth", "0005_remove_appusermodel_user")]

    operations = [
        migrations.CreateModel(
            name="EmailConfigModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(blank=True, max_length=100, unique=True)),
                ("from_email", models.EmailField(max_length=254)),
                ("provider", models.CharField(default="basic", max_length=100)),
                ("provider_package_name", models.CharField(blank=True, max_length=100)),
                (
                    "config",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        null=True, verbose_name="Config"
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="appauth.appusermodel",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="appauth.appusermodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EmailModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "message_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Message ID"
                    ),
                ),
                ("from_email", models.EmailField(max_length=254)),
                (
                    "to_email",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.EmailField(max_length=254),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "cc_email",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.EmailField(max_length=254),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "bcc_email",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.EmailField(max_length=254),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("email_body", models.TextField(blank=True)),
                (
                    "email_type",
                    models.CharField(
                        choices=[
                            ("IN", "Inbound"),
                            ("OUT", "Outbound"),
                            ("DR", "Draft"),
                        ],
                        default="DR",
                        max_length=3,
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("received_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "send_status",
                    models.CharField(
                        choices=[
                            ("staged", "Staged"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="staged",
                        max_length=10,
                    ),
                ),
                (
                    "send_responses",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, null=True
                    ),
                ),
                ("send_attempt_number", models.IntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="appauth.appusermodel",
                    ),
                ),
                (
                    "mail_config",
                    zelthy.apps.dynamic_models.fields.ZForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dynamic_models.emailconfigmodel",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="appauth.appusermodel",
                    ),
                ),
                (
                    "owner",
                    zelthy.apps.dynamic_models.fields.ZForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appauth.appusermodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SmsConfigModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(blank=True, max_length=100, unique=True)),
                (
                    "icon",
                    zelthy.core.storage_utils.ZFileField(
                        blank=True,
                        null=True,
                        upload_to=zelthy.core.storage_utils.local_save,
                        validators=[zelthy.core.storage_utils.validate_file_extension],
                    ),
                ),
                ("provider", models.CharField(max_length=100)),
                ("provider_package_name", models.CharField(max_length=100)),
                (
                    "config",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        verbose_name="Config"
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="appauth.appusermodel",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="appauth.appusermodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SMSTransactionsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "to_number",
                    models.CharField(
                        max_length=20, verbose_name="Recipient Phone Number"
                    ),
                ),
                (
                    "src",
                    models.CharField(
                        max_length=20, null=True, verbose_name="Source Mobile Number"
                    ),
                ),
                ("message", models.TextField(verbose_name="Message Content")),
                (
                    "date_sent",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date Sent"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("delivered", "Delivered"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=50,
                        verbose_name="Status",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Provider"
                    ),
                ),
                (
                    "response_code",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Response Code"
                    ),
                ),
                (
                    "response_text",
                    models.TextField(null=True, verbose_name="Response Text"),
                ),
                (
                    "is_test",
                    models.BooleanField(default=False, verbose_name="Is SMS Test"),
                ),
                (
                    "delivery_status",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Delivery Status",
                    ),
                ),
                (
                    "config",
                    zelthy.apps.dynamic_models.fields.ZForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="dynamic_models.smsconfigmodel",
                        verbose_name="Config",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="appauth.appusermodel",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="appauth.appusermodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EmailStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="appauth.appusermodel",
                    ),
                ),
                (
                    "email",
                    zelthy.apps.dynamic_models.fields.ZForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dynamic_models.emailmodel",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="appauth.appusermodel",
                    ),
                ),
                (
                    "user",
                    zelthy.apps.dynamic_models.fields.ZForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appauth.appusermodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EmailAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    zelthy.core.storage_utils.ZFileField(
                        upload_to=zelthy.core.storage_utils.local_save,
                        validators=[zelthy.core.storage_utils.validate_file_extension],
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=100)),
                ("size", models.PositiveIntegerField()),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="appauth.appusermodel",
                    ),
                ),
                (
                    "email",
                    zelthy.apps.dynamic_models.fields.ZForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="dynamic_models.emailmodel",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="appauth.appusermodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EmailAlternative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("content", models.TextField()),
                ("mime_type", models.CharField(max_length=100)),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="appauth.appusermodel",
                    ),
                ),
                (
                    "email",
                    zelthy.apps.dynamic_models.fields.ZForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alternatives",
                        to="dynamic_models.emailmodel",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="appauth.appusermodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CommmunicationActiveModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("sms", models.BooleanField(default=False)),
                ("email", models.BooleanField(default=False)),
                ("telephony", models.BooleanField(default=False)),
                ("imessage", models.BooleanField(default=False)),
                ("videocall", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="appauth.appusermodel",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="appauth.appusermodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunPython(create_default_active_status),
    ]