# Generated by Django 4.2.6 on 2024-01-05 18:00

from django.db import migrations, models
import uuid
from functools import partial


def create_uuid(apps, schema_editor, model):
    frames = apps.get_model("dynamic_models", model)
    for frame in frames.objects.all():
        frame.object_uuid = uuid.uuid4()
        frame.save()


class Migration(migrations.Migration):
    dependencies = [
        (
            "dynamic_models",
            "communication_0001_emailconfigmodel_emailmodel_smsconfigmodel_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="commmunicationactivemodel",
            name="object_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.RunPython(partial(create_uuid, model="commmunicationactivemodel")),
        migrations.AlterField(
            model_name="commmunicationactivemodel",
            name="object_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="emailalternative",
            name="object_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.RunPython(partial(create_uuid, model="emailalternative")),
        migrations.AlterField(
            model_name="emailalternative",
            name="object_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="emailattachment",
            name="object_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.RunPython(partial(create_uuid, model="emailattachment")),
        migrations.AlterField(
            model_name="emailattachment",
            name="object_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="emailconfigmodel",
            name="object_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.RunPython(partial(create_uuid, model="emailconfigmodel")),
        migrations.AlterField(
            model_name="emailconfigmodel",
            name="object_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="emailmodel",
            name="object_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.RunPython(partial(create_uuid, model="emailmodel")),
        migrations.AlterField(
            model_name="emailmodel",
            name="object_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="emailstatus",
            name="object_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.RunPython(partial(create_uuid, model="emailstatus")),
        migrations.AlterField(
            model_name="emailstatus",
            name="object_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="smsconfigmodel",
            name="object_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.RunPython(partial(create_uuid, model="smsconfigmodel")),
        migrations.AlterField(
            model_name="smsconfigmodel",
            name="object_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="smstransactionsmodel",
            name="object_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.RunPython(partial(create_uuid, model="smstransactionsmodel")),
        migrations.AlterField(
            model_name="smstransactionsmodel",
            name="object_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
