# Generated by Django 4.2.8 on 2024-01-11 12:15

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid
import zelthy.apps.dynamic_models.fields
import zelthy.core.storage_utils


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0005_remove_appusermodel_user'),
        ('dynamic_models', '0012_alter_doctor_user_alter_nurseeducator_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentmodel',
            name='reminders',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointmentmodel',
            name='video_call_details',
            field=models.JSONField(blank=True, null=True),
        )
    ]
