# Generated by Django 4.2.8 on 2024-01-03 11:35

from django.db import migrations, models
import django.db.models.deletion
import zelthy.apps.dynamic_models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0005_remove_appusermodel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginSignupConfigModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('config', models.JSONField()),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='appauth.appusermodel')),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='appauth.appusermodel')),
                ('user_role', zelthy.apps.dynamic_models.fields.ZOneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='login-signup', to='appauth.userrolemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
