# Generated by Django 4.2.8 on 2024-01-09 10:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid
import zelthy.apps.dynamic_models.fields
import zelthy.core.storage_utils


class Migration(migrations.Migration):
    dependencies = [
        (
            "dynamic_models",
            "communication_0004_remove_emailalternative_content_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TelephonyConfigModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "object_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("key", models.CharField(blank=True, max_length=100, unique=True)),
                (
                    "icon",
                    zelthy.core.storage_utils.ZFileField(
                        blank=True,
                        null=True,
                        upload_to=zelthy.core.storage_utils.local_save,
                        validators=[zelthy.core.storage_utils.validate_file_extension],
                    ),
                ),
                ("provider", models.CharField(max_length=100)),
                ("provider_package_name", models.CharField(max_length=100)),
                (
                    "config",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        verbose_name="Config"
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="appauth.appusermodel",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="appauth.appusermodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TelephonyAgent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "object_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("provider", models.CharField(max_length=100)),
                ("provider_package_name", models.CharField(max_length=100)),
                (
                    "config",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        verbose_name="Config"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="appauth.appusermodel",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="appauth.appusermodel",
                    ),
                ),
                (
                    "user",
                    zelthy.apps.dynamic_models.fields.ZForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user",
                        to="appauth.appusermodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CallRecordModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "object_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "destination_number",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Caller Number"
                    ),
                ),
                (
                    "agentId",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Agent Number"
                    ),
                ),
                (
                    "call_duration",
                    models.IntegerField(
                        null=True, verbose_name="Call Duration in Seconds"
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(null=True, verbose_name="Call Start Time"),
                ),
                ("end_time", models.DateTimeField(null=True, verbose_name="End Time")),
                (
                    "call_type",
                    models.CharField(
                        choices=[("incoming", "Incoming"), ("outgoing", "Outgoing")],
                        max_length=20,
                        null=True,
                        verbose_name="Call Type",
                    ),
                ),
                (
                    "call_record_url",
                    models.URLField(
                        blank=True,
                        null=True,
                        verbose_name="Call Record URL(Provider Server)",
                    ),
                ),
                (
                    "source_file_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Original File Name"
                    ),
                ),
                (
                    "call_record",
                    zelthy.core.storage_utils.ZFileField(
                        blank=True,
                        null=True,
                        upload_to=zelthy.core.storage_utils.local_save,
                        validators=[zelthy.core.storage_utils.validate_file_extension],
                        verbose_name="Call Record",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("knowlarity", "Knowlarity"),
                            ("exotel", "Exotel"),
                            ("ozonetel", "Ozonetel"),
                            ("aisth", "AIS Thailand"),
                            ("nice", "NICE"),
                        ],
                        max_length=100,
                        verbose_name="Telephony Provider",
                    ),
                ),
                (
                    "is_file_synced",
                    models.BooleanField(
                        default=False, verbose_name="Is mp3 file synced"
                    ),
                ),
                (
                    "extra_data",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, null=True
                    ),
                ),
                (
                    "response_text",
                    models.TextField(null=True, verbose_name="Response Text"),
                ),
                ("call_status", models.CharField(max_length=255)),
                (
                    "agent",
                    zelthy.apps.dynamic_models.fields.ZForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="dynamic_models.telephonyagent",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="appauth.appusermodel",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="appauth.appusermodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
