# Generated by Django 4.2.8 on 2024-01-09 03:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid
import zelthy.apps.dynamic_models.fields
import zelthy.core.storage_utils


class Migration(migrations.Migration):
    dependencies = [
        (
            "dynamic_models",
            "communication_0003_videocall",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailalternative",
            name="content",
        ),
        migrations.RemoveField(
            model_name="emailalternative",
            name="mime_type",
        ),
        migrations.AddField(
            model_name="emailalternative",
            name="alternative_body",
            field=models.TextField(blank=True, verbose_name="Alternative Body"),
        ),
        migrations.AddField(
            model_name="emailalternative",
            name="alternative_type",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Alternative Type"
            ),
        ),
        migrations.AddField(
            model_name="smstransactionsmodel",
            name="delivery_exception",
            field=models.TextField(null=True, verbose_name="Delivery Exception"),
        ),
        migrations.AlterField(
            model_name="emailstatus",
            name="user",
            field=zelthy.apps.dynamic_models.fields.ZForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="appauth.appusermodel",
            ),
        ),
    ]
