# Generated by Django 4.2.8 on 2024-01-04 11:37

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import zelthy.apps.dynamic_models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0005_remove_appusermodel_user'),
        ('dynamic_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('age', models.CharField(choices=[('12-17', '12-17'), ('18-59', '18-59'), ('>=60', '>=60')], max_length=10, verbose_name='Age')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10, verbose_name='Gender')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='appauth.appusermodel')),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='appauth.appusermodel')),
                ('user', zelthy.apps.dynamic_models.fields.ZForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appauth.appusermodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=zelthy.apps.dynamic_models.fields.ZForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appauth.appusermodel'),
        ),
        migrations.CreateModel(
            name='PatientProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('contact_person', models.CharField(choices=[('self', 'Self'), ('spouse', 'Spouse'), ('daughter', 'Daughter'), ('daughter-in-law', 'Daughter-in-law'), ('son', 'Son'), ('son-in-law', 'Son-in-law'), ('nephew', 'Nephew'), ('niece', 'Niece'), ('granddaughter', 'Granddaughter'), ('grandson', 'Grandson'), ('others', 'Others')], max_length=50, verbose_name='Contact Person')),
                ('contact_person_text', models.CharField(blank=True, null=True, verbose_name='Contact Person Text')),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Contact Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('prescribing_doctor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Doctor')),
                ('hospital_text', models.CharField(blank=True, null=True, verbose_name='Hospital Text')),
                ('years_since_diagnosis', models.CharField(choices=[('<=1 year', '<=1 year'), ('2-5 years', '2-5 years'), ('6-10 years', '6-10 years'), ('>10 years', '>10 years')], max_length=20, verbose_name='Years of Diagnosis')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='appauth.appusermodel')),
                ('doctor', zelthy.apps.dynamic_models.fields.ZForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dynamic_models.doctor')),
                ('hospital', zelthy.apps.dynamic_models.fields.ZForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dynamic_models.hospital')),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='appauth.appusermodel')),
                ('patient', zelthy.apps.dynamic_models.fields.ZForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dynamic_models.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
