# Generated by Django 4.2.8 on 2024-01-08 10:00

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0005_remove_appusermodel_user'),
        ('dynamic_models', '0006_patient_contact_number_patient_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('object_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('hosts', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), size=None)),
                ('participants', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), size=None)),
                ('appointment_type', models.CharField(choices=[('f2f', 'Face to Face'), ('video', 'Video'), ('telephonic', 'Telephonic')], default='f2f', max_length=10)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='mobile number')),
                ('coordinator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appauth.appusermodel')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='appauth.appusermodel')),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='appauth.appusermodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
