# Generated by Django 4.2.8 on 2024-01-10 12:33

from django.db import migrations, models
import django.db.models.deletion
import zelthy.apps.dynamic_models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0005_remove_appusermodel_user'),
        ('dynamic_models', '0011_doctor_consent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='user',
            field=zelthy.apps.dynamic_models.fields.ZForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='appauth.appusermodel'),
        ),
        migrations.AlterField(
            model_name='nurseeducator',
            name='user',
            field=zelthy.apps.dynamic_models.fields.ZForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nurse_educator', to='appauth.appusermodel'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='user',
            field=zelthy.apps.dynamic_models.fields.ZForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='appauth.appusermodel'),
        ),
        migrations.AlterField(
            model_name='patientprogram',
            name='training_type',
            field=models.CharField(blank=True, null=True, verbose_name='Training Type'),
        ),
    ]
