# Generated by Django 4.2.8 on 2024-01-11 12:23

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid
import zelthy.apps.dynamic_models.fields
import zelthy.core.storage_utils


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0005_remove_appusermodel_user'),
        ('dynamic_models', '0013_emailconfigmodel_emailmodel_meetinghostmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentmodel',
            name='stand_alone_meeting',
            field=models.BooleanField(default=False, verbose_name='Stand Alone Meeting'),
        )
    ]
