# Generated by Django 4.2.8 on 2024-01-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0014_emailconfigmodel_emailmodel_meetinghostmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='extra_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
