# Generated by Django 4.2.8 on 2024-01-06 05:54

from django.db import migrations, models
import django.db.models.deletion
import zelthy.apps.dynamic_models.fields
import zelthy.core.storage_utils


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0005_remove_appusermodel_user'),
        ('dynamic_models', '0002_patient_doctor_user_patientprogram'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdverseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('reported_by', models.CharField(choices=[('hcp', 'HCP'), ('patient', 'Patient'), ('caregiver', 'Caregiver')], max_length=50)),
                ('date_of_reporting', models.DateField()),
                ('summary', models.TextField()),
                ('attachment', zelthy.core.storage_utils.ZFileField(upload_to=zelthy.core.storage_utils.local_save, validators=[zelthy.core.storage_utils.validate_file_extension])),
                ('product', models.CharField(choices=[('dupixent_300mg', 'Dupixent 300mg'), ('dupixent_200mg', 'Dupixent 200mg')], max_length=50)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='appauth.appusermodel')),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='appauth.appusermodel')),
                ('patient', zelthy.apps.dynamic_models.fields.ZForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic_models.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
