# Generated by Django 4.2.8 on 2024-01-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0008_appointmentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='code',
            field=models.CharField(blank=True, null=True, verbose_name='Code'),
        ),
    ]
