# Generated by Django 4.2.8 on 2024-01-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0015_patient_extra_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.CharField(blank=True, choices=[('12-17', '12-17'), ('18-59', '18-59'), ('>=60', '>=60')], max_length=10, null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True, verbose_name='Gender'),
        ),
    ]
