# Generated by Django 4.2.4 on 2024-01-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dynamic_models", "qna_0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionsmodel",
            name="is_required",
            field=models.BooleanField(default=True),
        ),
    ]
